### ISSUE TITLE
index.php redirects to login when already logged in

### ISSUE THREAD

**Issue by Lezurex** [Z-100/Z-i-fy#23]
**Describe the bug**
When the user is logged in and navigates to "/php", the login screen appears.

**To Reproduce**
1. Go to "localhost/php"
2. JUST USE YOUR BRAIN

**Expected behavior**
Main page should appear/be found if logged in.

**Screenshots**
![image](https://user-images.githubusercontent.com/48829956/117349047-3d899700-aeab-11eb-81b5-af60ae139d47.png)

**Desktop (please complete the following information):**
 - OS: Windoof 11
 - Browser Chrome
 - Version doesn't matter

**Additional context**
Idk

**Comment by Z-100** [comment]
Fiexed it
