### ISSUE TITLE
Submit buttons are not localized in English

### ISSUE THREAD

**Issue by Lezurex** [Z-100/Z-i-fy#24]
**Describe the bug**
Submit buttons are not localized in English. When the client uses German locale, it appears in German, not in English (as the rest of the page).

**To Reproduce**
1. Open your eyes

**Expected behavior**
Englesh

**Screenshots**
![image](https://user-images.githubusercontent.com/48829956/117349620-e0421580-aeab-11eb-9f31-44d3fc9cdf9d.png)

**Comment by Z-100** [comment]
![image](https://user-images.githubusercontent.com/55056535/117404910-1498ee80-af0b-11eb-9c47-8dcac110d8bc.png)
Is it possible of you having any add-ons?
The submit button does currently not have any value="".
