### ISSUE TITLE
MySQLi error in home.php

### ISSUE THREAD

**Issue by Lezurex** [Z-100/Z-i-fy#25]
**Describe the bug**

Column 'thumbnail' cannot be found in table 'songs'.

Fatal error
: Uncaught mysqli_sql_exception: Unknown column 'songs.thumbnail' in 'field list' in C:\xampp\htdocs\Z-i-fy\php\home.php:43 Stack trace: #0 C:\xampp\htdocs\Z-i-fy\php\home.php(43): mysqli->query('SELECT songs.th...') #1 {main} thrown in
C:\xampp\htdocs\Z-i-fy\php\home.php
on line
43

**To Reproduce**
1. Open home.php

**Expected behavior**
No error.

**Comment by Z-100** [comment]
Is it possible, that you have an old version of the Database?
If so, I will be uploading a dump of the new one, for you to use

**Comment by Lezurex** [comment]
I've imported the most recent SQL dumps ser

**Comment by Z-100** [comment]
But ser, it's old

**Comment by Z-100** [comment]
The newest sql dump should be uploaded by now
